/* SuperNumber Lab front-end (rebuilt). No global `$`. Module + single-file. */
(function () {
  "use strict";

  /* ---------- Op catalogs (aligned with sn_web_bridge / sn_api) ---------- */
  const CATALOG = {
    const: [
      { type: "const_f", label: "浮点常量", hint: "任意 E/M + NaN" },
      { type: "const_i", label: "定宽整数", hint: "位宽 + 有/无符号" },
      { type: "const_bi", label: "大整数", hint: "无限精度 / 科学计数法" },
      { type: "const_c", label: "复数常量", hint: "re,im 或 a+bi" },
      { type: "out", label: "显示输出", hint: "打印结果" }
    ],
    arith: [
      { type: "bin", op: "add", label: "a + b" },
      { type: "bin", op: "sub", label: "a − b" },
      { type: "bin", op: "mul", label: "a × b" },
      { type: "bin", op: "div", label: "a ÷ b" },
      { type: "bin", op: "rem", label: "rem / fmod" },
      { type: "un", op: "neg", label: "−a" },
      { type: "un", op: "abs", label: "|a|" },
      { type: "ter", op: "fma", label: "fma(a,b,c)" },
      { type: "cast", op: "to_float", label: "cast→float" },
      { type: "cast", op: "to_int", label: "cast→int" },
      { type: "copy", op: "copy", label: "赋值/拷贝", hint: "sn_value 拷贝 (out = src)" },
      { type: "assign", op: "assign", label: "赋值传递", hint: "值拷贝，可串数据流" }
    ],
    math: [
      { type: "un", op: "sin", label: "sin" }, { type: "un", op: "cos", label: "cos" },
      { type: "un", op: "tan", label: "tan" }, { type: "un", op: "asin", label: "asin" },
      { type: "un", op: "acos", label: "acos" }, { type: "un", op: "atan", label: "atan" },
      { type: "bin", op: "atan2", label: "atan2(y,x)" },
      { type: "un", op: "sinh", label: "sinh" }, { type: "un", op: "cosh", label: "cosh" },
      { type: "un", op: "tanh", label: "tanh" }, { type: "un", op: "asinh", label: "asinh" },
      { type: "un", op: "acosh", label: "acosh" }, { type: "un", op: "atanh", label: "atanh" },
      { type: "un", op: "exp", label: "exp" }, { type: "un", op: "exp2", label: "exp2" },
      { type: "un", op: "expm1", label: "expm1" }, { type: "un", op: "log", label: "log" },
      { type: "un", op: "log2", label: "log2" }, { type: "un", op: "log10", label: "log10" },
      { type: "un", op: "log1p", label: "log1p" }, { type: "bin", op: "pow", label: "pow" },
      { type: "un", op: "sqrt", label: "sqrt" }, { type: "un", op: "cbrt", label: "cbrt" },
      { type: "bin", op: "hypot", label: "hypot" },
      { type: "un", op: "ceil", label: "ceil" }, { type: "un", op: "floor", label: "floor" },
      { type: "un", op: "trunc", label: "trunc" }, { type: "un", op: "rint", label: "rint" },
      { type: "un", op: "nearbyint", label: "nearbyint" },
      { type: "un", op: "erf", label: "erf" }, { type: "un", op: "erfc", label: "erfc" },
      { type: "un", op: "tgamma", label: "tgamma" }, { type: "un", op: "lgamma", label: "lgamma" },
      { type: "un", op: "digamma", label: "digamma" }, { type: "un", op: "trigamma", label: "trigamma" },
      { type: "bin", op: "fmin", label: "fmin" }, { type: "bin", op: "fmax", label: "fmax" },
      { type: "bin", op: "fdim", label: "fdim" },
      { type: "bin", op: "copysign", label: "copysign" }, { type: "bin", op: "nextafter", label: "nextafter" }
    ],
    bit: [
      { type: "bin", op: "and", label: "and" }, { type: "bin", op: "or", label: "or" },
      { type: "bin", op: "xor", label: "xor" }, { type: "un", op: "not", label: "not" },
      { type: "shift", op: "shl", label: "shl (左移)" },
      { type: "shift", op: "shr", label: "shr (逻辑右移)" },
      { type: "shift", op: "sar", label: "sar (算术右移)" },
      { type: "crypto", op: "gcd", label: "gcd", arity: 2 },
      { type: "crypto", op: "lcm", label: "lcm", arity: 2 },
      { type: "crypto", op: "isqrt", label: "isqrt", arity: 1 },
      { type: "crypto", op: "popcount", label: "popcount", arity: 1 },
      { type: "crypto", op: "ctz", label: "ctz", arity: 1 },
      { type: "crypto", op: "modinv", label: "modinv", arity: 2 },
      { type: "crypto", op: "mulmod", label: "mulmod", arity: 3 },
      { type: "crypto", op: "powmod", label: "powmod", arity: 3 },
      { type: "crypto", op: "powmod_ct", label: "powmod_ct", arity: 3 }
    ],
    spec: [
      { type: "un", op: "j0", label: "j0" }, { type: "un", op: "j1", label: "j1" },
      { type: "un", op: "y0", label: "y0" }, { type: "un", op: "y1", label: "y1" },
      { type: "un", op: "i0", label: "i0" }, { type: "un", op: "i1", label: "i1" },
      { type: "un", op: "k0", label: "k0" }, { type: "un", op: "k1", label: "k1" },
      { type: "un", op: "ellipk", label: "K(m)" }, { type: "un", op: "ellipe", label: "E(m)" },
      { type: "bin", op: "ellipf", label: "F(φ|m)" }, { type: "bin", op: "ellipeinc", label: "E(φ|m)" },
      { type: "ter", op: "ellipiinc", label: "Π(n;φ|m)" },
      { type: "bin", op: "igamma", label: "igamma P" }, { type: "bin", op: "igammac", label: "igammac Q" },
      { type: "bin", op: "jacobi_sn", label: "sn(u|m)" }, { type: "bin", op: "jacobi_cn", label: "cn(u|m)" },
      { type: "bin", op: "jacobi_dn", label: "dn(u|m)" },
      { type: "ter", op: "ibeta", label: "ibeta" }, { type: "ter", op: "ibetac", label: "ibetac" }
    ],
    cplx: [
      { type: "cbin", op: "add", label: "c +" }, { type: "cbin", op: "sub", label: "c −" },
      { type: "cbin", op: "mul", label: "c ×" }, { type: "cbin", op: "div", label: "c ÷" },
      { type: "cbin", op: "pow", label: "cpow" },
      { type: "cun", op: "neg", label: "cneg" }, { type: "cun", op: "conj", label: "conj" },
      { type: "cun", op: "proj", label: "proj" }, { type: "cun", op: "sqrt", label: "csqrt" },
      { type: "cun", op: "exp", label: "cexp" }, { type: "cun", op: "log", label: "clog" },
      { type: "cun", op: "sin", label: "csin" }, { type: "cun", op: "cos", label: "ccos" },
      { type: "cun", op: "tan", label: "ctan" }, { type: "cun", op: "sinh", label: "csinh" },
      { type: "cun", op: "cosh", label: "ccosh" }, { type: "cun", op: "tanh", label: "ctanh" },
      { type: "cun", op: "asin", label: "casin" }, { type: "cun", op: "acos", label: "cacos" },
      { type: "cun", op: "atan", label: "catan" }, { type: "cun", op: "asinh", label: "casinh" },
      { type: "cun", op: "acosh", label: "cacosh" }, { type: "cun", op: "atanh", label: "catanh" },
      { type: "c2r", op: "re", label: "Re" }, { type: "c2r", op: "im", label: "Im" },
      { type: "c2r", op: "abs", label: "|z|" }, { type: "c2r", op: "arg", label: "arg" },
      { type: "r2c", op: "set_reim", label: "re+im·i" },
      { type: "r2c", op: "from_polar", label: "ρ∠θ" }
    ],
    flow: [
      /* UE-style exec control flow */
      { type: "entry", op: "entry", label: "Entry" },
      { type: "branch", op: "branch", label: "Branch / If" },
      { type: "while", op: "while", label: "While Loop" },
      { type: "for", op: "for", label: "For Loop" },
      { type: "sequence", op: "sequence", label: "Sequence" },
      { type: "do_once", op: "do_once", label: "DoOnce" },
      { type: "do_n", op: "do_n", label: "DoN" },
      { type: "gate", op: "gate", label: "Gate" },
      { type: "flip_flop", op: "flip_flop", label: "FlipFlop" },
      { type: "multi_gate", op: "multi_gate", label: "MultiGate" },
      { type: "switch", op: "switch", label: "Switch" },
      { type: "break", op: "break", label: "Break Loop" },
      { type: "continue", op: "continue", label: "Continue Loop" },
      { type: "reroute", op: "reroute", label: "Reroute (exec)" },
      { type: "do_while", op: "do_while", label: "DoWhile" },
      { type: "select_exec", op: "select_exec", label: "Select (exec)" },
      { type: "comment", op: "comment", label: "注释 / Comment" },
      { type: "set_var", op: "set", label: "Set var" },
      { type: "get_var", op: "get", label: "Get var" },
      { type: "print", op: "print", label: "Print" },
      { type: "out", op: "out", label: "Output (Print+exec)" },
      /* pure data select / compare / logic */
      { type: "cmp", op: "eq", label: "a == b" },
      { type: "cmp", op: "ne", label: "a != b" },
      { type: "cmp", op: "lt", label: "a < b" },
      { type: "cmp", op: "le", label: "a <= b" },
      { type: "cmp", op: "gt", label: "a > b" },
      { type: "cmp", op: "ge", label: "a >= b" },
      { type: "select", op: "select", label: "select(cond,then,else)" },
      { type: "logic", op: "and", label: "and" },
      { type: "logic", op: "or", label: "or" },
      { type: "logic", op: "xor", label: "xor" },
      { type: "logic", op: "not", label: "not" },
      { type: "logic", op: "nand", label: "nand" },
      { type: "logic", op: "nor", label: "nor" },
      { type: "logic", op: "xnor", label: "xnor" },
      { type: "logic", op: "implies", label: "implies (a→b)" },
      { type: "const_bool", op: "true", label: "true (1)" },
      { type: "const_bool", op: "false", label: "false (0)" },
      { type: "rng", op: "u64", label: "random u64" },
      { type: "rng", op: "u64_mod", label: "random [0,n)" },
      { type: "rng", op: "seed", label: "seed RNG" },
      { type: "cast", op: "to_float", label: "cast → float" },
      { type: "cast", op: "to_int", label: "cast → int" }
    ],
    data: [
      { type: "arr_lit", label: "Make Array", hint: "分号/逗号/空格分隔元素；或 JSON [..]" },
      { type: "vec_lit", label: "Make Vector", hint: "一维向量字面量" },
      { type: "mat_lit", label: "Make Matrix", hint: "行用 ; 分隔，列用 , 分隔" },
      { type: "arr_len", label: "Len", hint: "数组/向量长度" },
      { type: "arr_get", label: "Get [i]", hint: "按索引取元素" },
      { type: "arr_set", label: "Set [i]=v", hint: "返回新数组（不可变）" },
      { type: "arr_push", label: "Push", hint: "追加元素 → 新数组" },
      { type: "arr_slice", label: "Slice", hint: "slice(start,end) 半开区间" },
      { type: "arr_concat", label: "Concat", hint: "连接两个数组/向量" },
      { type: "arr_map", label: "Map +const", hint: "每个元素 + 标量（可改 op）" },
      { type: "arr_reduce", label: "Reduce sum", hint: "求和 / 积" },
      { type: "vec_dot", label: "Dot", hint: "向量点积 a·b" },
      { type: "vec_scale", label: "Scale", hint: "向量 × 标量" },
      { type: "vec_add", label: "Vec add", hint: "逐元相加" },
      { type: "mat_mul", label: "MatMul", hint: "矩阵乘法 A×B" },
      { type: "mat_dims", label: "Mat dims", hint: "输出 rows/cols（rows 在 out）" },
      { type: "mat_get", label: "Mat get", hint: "A[r,c]" },
      { type: "mat_set", label: "Mat set", hint: "返回新矩阵" },
      { type: "mat_transpose", label: "Transpose", hint: "Aᵀ" },
      { type: "mat_identity", label: "Identity", hint: "n×n 单位阵" },
      { type: "arr_from_range", label: "Range", hint: "整数序列 first..last" },
      /* elementwise / reshape / ML primitives (web tensor runtime) */
      { type: "mat_add", label: "Mat add", hint: "逐元 A+B（可广播）" },
      { type: "mat_sub", label: "Mat sub", hint: "逐元 A−B" },
      { type: "mat_hadamard", label: "Hadamard", hint: "逐元 A⊙B" },
      { type: "mat_scale", label: "Mat scale", hint: "矩阵/向量 × 标量" },
      { type: "ten_unary", label: "Ten unary", hint: "逐元 exp/relu/gelu/tanh/…" },
      { type: "ten_binop", label: "Ten binop", hint: "逐元 add/sub/mul/div" },
      { type: "mat_row_sum", label: "Row sum", hint: "按行求和 → 列向量" },
      { type: "mat_row_mean", label: "Row mean", hint: "按行均值" },
      { type: "mat_row_max", label: "Row max", hint: "按行最大值" },
      { type: "softmax_row", label: "Softmax row", hint: "按行 softmax（数值稳定）" },
      { type: "layer_norm", label: "LayerNorm", hint: "末维归一化 + γ/β 可选" },
      { type: "rms_norm", label: "RMSNorm", hint: "RMS 归一化" },
      { type: "reshape", label: "Reshape", hint: "改形状，元素总数不变" },
      { type: "flatten", label: "Flatten", hint: "矩阵/向量 → 一维" },
      { type: "mat_concat", label: "Mat concat", hint: "沿 axis 拼接" },
      { type: "mat_slice", label: "Mat slice", hint: "子矩阵 [r0:r1, c0:c1)" },
      { type: "mat_outer", label: "Outer", hint: "外积 a bᵀ" },
      { type: "mat_diag", label: "Diag", hint: "向量→对角 / 矩阵→对角" },
      { type: "gather", label: "Gather", hint: "按索引从表中取行（embedding）" },
      { type: "embedding", label: "Embedding", hint: "token ids → 查表（同 gather）" },
      { type: "sin_pe", label: "Sin PE", hint: "正弦位置编码 [seq×d]" },
      { type: "attention_sdp", label: "SDPA", hint: "scaled dot-product attention" },
      { type: "mha_split", label: "MHA split", hint: "[seq×d] 按 head 拆分再水平拼" },
      { type: "mha_merge", label: "MHA merge", hint: "多 head 拼回 [seq×d]" },
      { type: "gelu", label: "GELU", hint: "GELU 激活" },
      { type: "relu", label: "ReLU", hint: "max(0,x) 逐元" },
      { type: "silu", label: "SiLU", hint: "x·sigmoid(x) / Swish（Qwen3 FFN）" },
      { type: "swiglu", label: "SwiGLU", hint: "SiLU(gate)⊙up（门控 FFN）" },
      { type: "rope", label: "RoPE", hint: "旋转位置编码（Qwen3 用）" },
      { type: "residual_add", label: "Residual +", hint: "x + y（残差）" }
    ]
  };

  const LABELS = {
    digamma: "ψ digamma", trigamma: "ψ₁ trigamma",
    ellipk: "K(m)", ellipe: "E(m)", ellipf: "F(φ|m)", ellipeinc: "E(φ|m)",
    ellipiinc: "Π(n;φ|m)", igamma: "P(a,x)", igammac: "Q(a,x)",
    jacobi_sn: "sn(u|m)", jacobi_cn: "cn(u|m)", jacobi_dn: "dn(u|m)",
    ibeta: "Iₓ(a,b)", ibetac: "1−Iₓ", set_reim: "re+im·i", from_polar: "ρ∠θ",
    re: "Re", im: "Im", abs: "|·|", arg: "arg",
    shl: "shl", shr: "shr", sar: "sar",
    to_float: "→float", to_int: "→int",
    copy: "Copy", assign: "Assign",
    gcd: "gcd", lcm: "lcm", isqrt: "isqrt", popcount: "popcount", ctz: "ctz", modinv: "modinv", mulmod: "mulmod", powmod: "powmod", powmod_ct: "powmod_ct",
    eq: "==", ne: "!=", lt: "<", le: "<=", gt: ">", ge: ">=",
    select: "select", nand: "nand", nor: "nor", xnor: "xnor", implies: "⇒",
    entry: "Entry", branch: "Branch", while: "While", for: "For", sequence: "Sequence",
    do_once: "DoOnce", do_n: "DoN", gate: "Gate", flip_flop: "FlipFlop", multi_gate: "MultiGate",
    switch: "Switch", break: "Break", continue: "Continue", reroute: "Reroute",
    do_while: "DoWhile", select_exec: "SelectExec", comment: "注释",
    set: "Set", get: "Get", print: "Print", out: "Output",
    u64: "rand u64", u64_mod: "rand mod", seed: "seed RNG",
    true: "true", false: "false",
    arr_lit: "Array", vec_lit: "Vector", mat_lit: "Matrix",
    arr_len: "Len", arr_get: "Get", arr_set: "Set", arr_push: "Push",
    arr_slice: "Slice", arr_concat: "Concat", arr_map: "Map", arr_reduce: "Reduce",
    vec_dot: "Dot", vec_scale: "Scale", vec_add: "Vec+",
    mat_mul: "MatMul", mat_dims: "Dims", mat_get: "M[r,c]", mat_set: "M set",
    mat_transpose: "Aᵀ", mat_identity: "Iₙ", arr_from_range: "Range",
    mat_add: "A+B", mat_sub: "A−B", mat_hadamard: "A⊙B", mat_scale: "A×s",
    ten_unary: "f(·)", ten_binop: "a∘b", mat_row_sum: "Σrow", mat_row_mean: "μrow",
    mat_row_max: "maxrow", softmax_row: "softmax", layer_norm: "LayerNorm",
    rms_norm: "RMSNorm", reshape: "Reshape", flatten: "Flatten",
    mat_concat: "Concat", mat_slice: "Slice2D", mat_outer: "Outer", mat_diag: "Diag",
    gather: "Gather", embedding: "Embed", sin_pe: "SinPE", attention_sdp: "SDPA",
    mha_split: "MHA↦", mha_merge: "MHA↤", gelu: "GELU", relu: "ReLU",
    silu: "SiLU", swiglu: "SwiGLU", rope: "RoPE",
    residual_add: "x+y"
  };

  /* LABELS/CATALOG end — runtime continues in 02-runtime.js (same IIFE when assembled) */
